# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab0c3e62dac31436376fe78f106d41c9f80e4882fc352f6c03ce22b9a283c87a6c8b7f0113ee092b2b49e47b6068dc718d1b155fccb0aa687a4bb35442055a92

test:
  secret_key_base: a4148e04dbaa47faf415fe590b3bbe6a992437a46fe55a7ea990743ae694894b75e4128f2d773507c4fb7e59ff0bf31c84f6ae8aef0006d62019abde5603c6ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
